#!/usr/bin/env node

require('../publish')(__dirname);

// const execa = require('execa');
// const path = require('path');
// const { writeFile } = require('then-fs');
// const package = require('./package');

// const cwd = __dirname;

// async function main() {
//   const version = await bumpVersion();
//   await execa('git', ['add', '*'], {cwd});
//   await execa('git', ['commit', '-am', '🚀 ' + version], {cwd});
//   await execa('git', ['push', 'origin', 'master'], {cwd});
//   await execa('npm', ['publish', '--access=public'], {cwd});
//   console.log(`@simplej/rapid-plop version ${version} published`);
  
//   return version;
// }

// async function bumpVersion() {
//   const [ major, minor, patch ] = package.version.split(/\./g).map(n => +n);
//   package.version = `${major}.${minor}.${patch + 1}`;
//   await writeFile(path.join(__dirname, 'package.json'), JSON.stringify(package, null, 2));
//   return package.version;
// }

// module.exports = main();
